I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 35, in script
    play sound "audio/Car.ogg" volume 1.0 fadein fadeout
  File "renpy/common/000statements.rpy", line 292, in execute_play_sound
    fadein=eval(p["fadein"]),
  File "game/script.rpy", line 35, in <module>
    play sound "audio/Car.ogg" volume 1.0 fadein fadeout
NameError: name 'fadeout' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 35, in script
    play sound "audio/Car.ogg" volume 1.0 fadein fadeout
  File "renpy/ast.py", line 1969, in execute
    self.call("execute")
  File "renpy/ast.py", line 1957, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "renpy/statements.py", line 278, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 292, in execute_play_sound
    fadein=eval(p["fadein"]),
  File "renpy/python.py", line 2249, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2242, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 35, in <module>
    play sound "audio/Car.ogg" volume 1.0 fadein fadeout
NameError: name 'fadeout' is not defined

Windows-10-10.0.18362
Ren'Py 7.4.2.1292
Red Scarf 1.0
Sat Feb 13 07:34:59 2021
